### ISSUE TITLE
Usage in tree

### ISSUE THREAD

**Issue by Havunen** [vthib/tlsh#12]
Hi, 

My use case is following:
I would like store thousands to tens of thousands of these tlsh objects and then later after creating new one I would like to find the most similar tlsh object from these stored ones as fast as possible. And if none of them match up to a certain diff value I will store that to the storage. 

Is it possible to have sorted binary tree or similar datastructure for comparing the tlsh objects or is vector and linear scan the only way?

**Comment by vthib** [comment]
Hello. It is indeed possible because the "diff" is actually a distance in the mathematical sense, and thus existing hashes can be arranged to get logarithmic lookups for nearest neighbor. The tlsh website gives a few pointers as to how to implement this: https://tlsh.org/papers.html
